OBJS = ../util/sdram.o ../util/clock.o ../util/console.o lcd-spi.o ../util/gfx.o

BINARY = lcd-serial

# we use sin/cos from the library
LDLIBS += -lm

DEVICE = STM32F429ZI

include ../../Makefile.include
